events {}

http {
    # -----------------------------
    #  Upstreams
    # -----------------------------
    upstream auth_service {
        server 127.0.0.1:4000;
    }

    upstream habit_service {
        server 127.0.0.1:8001;
    }

    server {
        listen 9000;

        # -------- AUTH SERVICE ---------
        # Incoming:  /api/auth/...
        # Outgoing:  http://127.0.0.1:4000/api/auth/...
        location /api/auth/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # -------- HABIT SERVICE ---------
        # Incoming:  /api/habits/...
        # Outgoing:  http://127.0.0.1:8001/api/habits/...
        location /api/habits/ {
            proxy_pass http://habit_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
